services:
  postgres:
    image: postgres:latest  # ใช้ Dockerfile จากโฟลเดอร์นี้
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=easyflowdb
      - POSTGRES_TIMEZONE=Asia/Bangkok
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app_network


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    restart: always
    networks:
      - app_network  

networks:
  app_network:  # สร้าง network ชื่อว่า app_network
    driver: bridge  # ใช้ driver แบบ bridge
